'use client'

import { useState } from 'react'
import { WOD_FORMATS, SCORING_TYPES, clockToSeconds } from '../lib/constants'
import { sanitizeText, wodSchema } from '../lib/security'
import VideoUploadField from './VideoUploadField'

function secondsToClock(seconds) { if (seconds == null) return ''; return `${Math.floor(seconds / 60)}:${String(seconds % 60).padStart(2, '0')}` }

export default function WodEditForm({ wod, userId, onSubmit, onCancel }) {
  const [title, setTitle] = useState(wod.title || ''); const [format, setFormat] = useState(wod.format || 'for_time'); const [scoringType, setScoringType] = useState(wod.scoring_type || 'time'); const [description, setDescription] = useState(wod.description || ''); const [wodDate, setWodDate] = useState(wod.wod_date || ''); const [timeCap, setTimeCap] = useState(secondsToClock(wod.time_cap_sec)); const [emomInterval, setEmomInterval] = useState(wod.emom_interval_sec ?? 60); const [emomRounds, setEmomRounds] = useState(wod.emom_rounds ?? ''); const [isBenchmark, setIsBenchmark] = useState(Boolean(wod.is_benchmark)); const [videoUrl, setVideoUrl] = useState(wod.video_url || ''); const [saving, setSaving] = useState(false); const [error, setError] = useState(null)
  async function handleSubmit(event) {
    event.preventDefault(); setError(null)
    const parsed = wodSchema.safeParse({ title: sanitizeText(title, 120), format, scoring_type: scoringType, description: sanitizeText(description, 3000), wod_date: wodDate, time_cap_sec: timeCap ? clockToSeconds(timeCap) : null, emom_interval_sec: format === 'emom' ? Number(emomInterval) : null, emom_rounds: format === 'emom' && emomRounds !== '' ? Number(emomRounds) : null, is_benchmark: isBenchmark, video_url: videoUrl ? sanitizeText(videoUrl, 500) : null })
    if (!parsed.success) { setError('Vérifie les champs et les limites de valeurs.'); return }
    setSaving(true); try { await onSubmit(parsed.data) } catch { setError('Impossible d’enregistrer les modifications.') } finally { setSaving(false) }
  }
  return <form onSubmit={handleSubmit} className="stack"><div><label htmlFor="edit-title">Titre</label><input id="edit-title" value={title} onChange={(e) => setTitle(e.target.value)} maxLength={120} required /></div><div><label htmlFor="edit-date">Date</label><input id="edit-date" type="date" value={wodDate} onChange={(e) => setWodDate(e.target.value)} required /></div><div><label htmlFor="edit-format">Format</label><select id="edit-format" value={format} onChange={(e) => setFormat(e.target.value)}>{WOD_FORMATS.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></div>{format === 'emom' && <div className="fieldGrid"><div><label htmlFor="edit-interval">Intervalle (sec)</label><input id="edit-interval" type="number" min="1" max="3600" value={emomInterval} onChange={(e) => setEmomInterval(e.target.value)} required /></div><div><label htmlFor="edit-rounds">Nb rounds</label><input id="edit-rounds" type="number" min="1" max="200" value={emomRounds} onChange={(e) => setEmomRounds(e.target.value)} required /></div></div>}{(format === 'for_time' || format === 'amrap') && <div><label htmlFor="edit-cap">Time cap (mm:ss, optionnel)</label><input id="edit-cap" value={timeCap} onChange={(e) => setTimeCap(e.target.value)} inputMode="numeric" pattern="[0-9]{1,3}:[0-5][0-9]" /></div>}<div><label htmlFor="edit-description">Description du WOD</label><textarea id="edit-description" rows={6} maxLength={3000} value={description} onChange={(e) => setDescription(e.target.value)} required /></div><div><label htmlFor="edit-video">Lien vidéo (démo technique, optionnel)</label><input id="edit-video" type="url" value={videoUrl} onChange={(e) => setVideoUrl(e.target.value)} placeholder="https://..." maxLength={500} /><VideoUploadField userId={userId} folder="wod-videos" onUploaded={setVideoUrl} /></div><div><label htmlFor="edit-scoring">Type de score attendu</label><select id="edit-scoring" value={scoringType} onChange={(e) => setScoringType(e.target.value)}>{SCORING_TYPES.map((item) => <option key={item.value} value={item.value}>{item.label}</option>)}</select></div><label style={{ display: 'flex', alignItems: 'center', gap: 8, textTransform: 'none', cursor: 'pointer' }}><input type="checkbox" style={{ width: 'auto' }} checked={isBenchmark} onChange={(e) => setIsBenchmark(e.target.checked)} /><span style={{ fontSize: 14, color: 'var(--chalk)' }}>C’est un WOD benchmark</span></label>{error && <div className="errorBox" role="alert">{error}</div>}<div className="row" style={{ gap: 8 }}><button type="button" className="btn btnGhost" onClick={onCancel} disabled={saving}>Annuler</button><button type="submit" className="btn btnPrimary" style={{ flex: 1 }} disabled={saving}>{saving ? '…' : 'Enregistrer les modifications'}</button></div></form>
}
